# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "rss"
name = "RSS"
url = "https://blog.fzf404.top/index.xml"

[social.params]
icon = "rss"

[[social]]
identifier = "home"
name = "Home"
url = "https://www.fzf404.top"

[social.params]
icon = "home"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/fzf404"

[social.params]
icon = "brand-github"
